apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: peer0-netflix-myapp-com
  name: peer0-netflix-myapp-com
spec:
  ports:
  - name: "7051"
    port: 7051
    targetPort: 7051
  - name: "7052"
    port: 7052
    targetPort: 7052
  - name: "7053"
    port: 7053
    targetPort: 7053
  selector:
    io.kompose.service: peer0-netflix-myapp-com
status:
  loadBalancer: {}
